"""create account asset trade tables

Revision ID: 2e3b2ebec6d5
Revises: 484cf4edb40f
Create Date: 2026-07-06 18:51:39.870342
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3b2ebec6d5'
down_revision: Union[str, None] = '484cf4edb40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('broker', sa.Text(), nullable=True),
    sa.Column('account_type', sa.Text(), nullable=True),
    sa.Column('base_currency', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_accounts_status'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('name', name=op.f('uq_accounts_name'))
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_assets_market_id_markets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('symbol', 'market_id', name='uq_assets_symbol_market')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('entry_price', sa.REAL(), nullable=False),
    sa.Column('quantity', sa.REAL(), nullable=False),
    sa.Column('entry_datetime', sa.Text(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('market_session_id', sa.Integer(), nullable=True),
    sa.Column('timeframe_id', sa.Integer(), nullable=True),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('setup_id', sa.Integer(), nullable=True),
    sa.Column('risk_profile_id', sa.Integer(), nullable=True),
    sa.Column('trading_session_id', sa.Integer(), nullable=True),
    sa.Column('exit_price', sa.REAL(), nullable=True),
    sa.Column('exit_datetime', sa.Text(), nullable=True),
    sa.Column('stop_loss', sa.REAL(), nullable=True),
    sa.Column('take_profit', sa.REAL(), nullable=True),
    sa.Column('position_size', sa.REAL(), nullable=True),
    sa.Column('commission', sa.REAL(), nullable=False),
    sa.Column('swap_fees', sa.REAL(), nullable=False),
    sa.Column('risk_amount', sa.REAL(), nullable=True),
    sa.Column('editable_until', sa.Text(), nullable=True),
    sa.Column('notes_override', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.CheckConstraint("direction IN ('long', 'short')", name='ck_trades_direction'),
    sa.CheckConstraint("status IN ('open', 'closed')", name='ck_trades_status'),
    sa.CheckConstraint('commission >= 0', name='ck_trades_commission'),
    sa.CheckConstraint('entry_price > 0', name='ck_trades_entry_price'),
    sa.CheckConstraint('position_size >= 0', name='ck_trades_position_size'),
    sa.CheckConstraint('quantity > 0', name='ck_trades_quantity'),
    sa.CheckConstraint('swap_fees >= 0', name='ck_trades_swap_fees'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_trades_account_id_accounts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_trades_asset_id_assets'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], name=op.f('fk_trades_broker_id_brokers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_session_id'], ['market_sessions.id'], name=op.f('fk_trades_market_session_id_market_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name=op.f('fk_trades_timeframe_id_timeframes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_trades_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], name=op.f('fk_trades_setup_id_setups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['risk_profile_id'], ['risk_profiles.id'], name=op.f('fk_trades_risk_profile_id_risk_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trading_session_id'], ['trading_sessions.id'], name=op.f('fk_trades_trading_session_id_trading_sessions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index('ix_trades_account_id', 'trades', ['account_id'], unique=False)
    op.create_index('ix_trades_asset_entry_datetime', 'trades', ['asset_id', 'entry_datetime'], unique=False)
    op.create_index('ix_trades_asset_id', 'trades', ['asset_id'], unique=False)
    op.create_index('ix_trades_broker_id', 'trades', ['broker_id'], unique=False)
    op.create_index('ix_trades_direction', 'trades', ['direction'], unique=False)
    op.create_index('ix_trades_entry_datetime', 'trades', ['entry_datetime'], unique=False)
    op.create_index('ix_trades_exit_datetime', 'trades', ['exit_datetime'], unique=False)
    op.create_index('ix_trades_market_session_id', 'trades', ['market_session_id'], unique=False)
    op.create_index('ix_trades_risk_profile_id', 'trades', ['risk_profile_id'], unique=False)
    op.create_index('ix_trades_setup_id', 'trades', ['setup_id'], unique=False)
    op.create_index('ix_trades_status_entry_datetime', 'trades', ['status', 'entry_datetime'], unique=False)
    op.create_index('ix_trades_strategy_entry_datetime', 'trades', ['strategy_id', 'entry_datetime'], unique=False)
    op.create_index('ix_trades_strategy_id', 'trades', ['strategy_id'], unique=False)
    op.create_index('ix_trades_timeframe_id', 'trades', ['timeframe_id'], unique=False)
    op.create_index('ix_trades_trading_session_id', 'trades', ['trading_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_trading_session_id', table_name='trades')
    op.drop_index('ix_trades_timeframe_id', table_name='trades')
    op.drop_index('ix_trades_strategy_id', table_name='trades')
    op.drop_index('ix_trades_strategy_entry_datetime', table_name='trades')
    op.drop_index('ix_trades_status_entry_datetime', table_name='trades')
    op.drop_index('ix_trades_setup_id', table_name='trades')
    op.drop_index('ix_trades_risk_profile_id', table_name='trades')
    op.drop_index('ix_trades_market_session_id', table_name='trades')
    op.drop_index('ix_trades_exit_datetime', table_name='trades')
    op.drop_index('ix_trades_entry_datetime', table_name='trades')
    op.drop_index('ix_trades_direction', table_name='trades')
    op.drop_index('ix_trades_broker_id', table_name='trades')
    op.drop_index('ix_trades_asset_id', table_name='trades')
    op.drop_index('ix_trades_asset_entry_datetime', table_name='trades')
    op.drop_index('ix_trades_account_id', table_name='trades')
    op.drop_table('trades')
    op.drop_table('assets')
    op.drop_table('accounts')
    # ### end Alembic commands ###
