"""create psychology review trading session tables

Revision ID: 93fa025b4e22
Revises: 970bf55b0d74
Create Date: 2026-07-06 19:12:28.448446
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fa025b4e22'
down_revision: Union[str, None] = '970bf55b0d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emotions')),
    sa.UniqueConstraint('name', name=op.f('uq_emotions_name'))
    )
    op.create_table('mistakes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistakes')),
    sa.UniqueConstraint('name', name=op.f('uq_mistakes_name'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('trading_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_datetime', sa.Text(), nullable=False),
    sa.Column('end_datetime', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trading_sessions'))
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.CheckConstraint("type IN ('image')", name='ck_attachments_type'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_attachments_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_table('emotion_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("context IN ('before_entry', 'during_trade', 'after_exit')", name='ck_emotion_entries_context'),
    sa.CheckConstraint('intensity BETWEEN 1 AND 10', name='ck_emotion_entries_intensity'),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], name=op.f('fk_emotion_entries_emotion_id_emotions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_emotion_entries_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emotion_entries'))
    )
    op.create_index('ix_emotion_entries_emotion_id', 'emotion_entries', ['emotion_id'], unique=False)
    op.create_table('mistake_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('mistake_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mistake_id'], ['mistakes.id'], name=op.f('fk_mistake_entries_mistake_id_mistakes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_mistake_entries_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistake_entries'))
    )
    op.create_index('ix_mistake_entries_mistake_id', 'mistake_entries', ['mistake_id'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_notes_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_table('trade_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('lesson_learned', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_trade_reviews_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trade_reviews'))
    )
    op.create_table('trade_tags',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_trade_tags_tag_id_tags'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_trade_tags_trade_id_trades'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id', 'tag_id', name=op.f('pk_trade_tags'))
    )
    op.create_index('ix_trade_tags_tag_id', 'trade_tags', ['tag_id'], unique=False)
    # NOTE: The FK constraints on trades (strategy_id → strategies, setup_id → setups,
    # risk_profile_id → risk_profiles, trading_session_id → trading_sessions) were
    # already created inline in the PR 2 migration (2e3b2ebec6d5). The ORM model
    # currently uses plain Integer for these columns, but the DB has the FKs.
    # Do NOT drop or recreate them here — they already exist and work.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trade_tags_tag_id', table_name='trade_tags')
    op.drop_table('trade_tags')
    op.drop_table('trade_reviews')
    op.drop_table('notes')
    op.drop_index('ix_mistake_entries_mistake_id', table_name='mistake_entries')
    op.drop_table('mistake_entries')
    op.drop_index('ix_emotion_entries_emotion_id', table_name='emotion_entries')
    op.drop_table('emotion_entries')
    op.drop_table('attachments')
    op.drop_table('trading_sessions')
    op.drop_table('tags')
    op.drop_table('mistakes')
    op.drop_table('emotions')
    # ### end Alembic commands ###
