"""create strategy cluster tables

Revision ID: 970bf55b0d74
Revises: 2e3b2ebec6d5
Create Date: 2026-07-06 19:04:17.067982
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '970bf55b0d74'
down_revision: str | None = '2e3b2ebec6d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setups')),
    sa.UniqueConstraint('name', name='uq_setups_name')
    )
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies')),
    sa.UniqueConstraint('name', name='uq_strategies_name')
    )
    op.create_table('risk_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('max_risk_per_trade', sa.REAL(), nullable=True),
    sa.Column('position_sizing_method', sa.Text(), nullable=True),
    sa.Column('max_daily_loss', sa.REAL(), nullable=True),
    sa.Column('max_concurrent_trades', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_risk_profiles_strategy_id_strategies'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_profiles'))
    )
    op.create_index('ix_risk_profiles_strategy_id', 'risk_profiles', ['strategy_id'], unique=False)
    op.create_table('strategy_setups',
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('setup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['setup_id'], ['setups.id'], name=op.f('fk_strategy_setups_setup_id_setups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_setups_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('strategy_id', 'setup_id', name=op.f('pk_strategy_setups'))
    )
    op.create_index('ix_strategy_setups_setup_id', 'strategy_setups', ['setup_id'], unique=False)
    # NOTE: FK constraints on trades (strategy_id → strategies, setup_id → setups,
    # risk_profile_id → risk_profiles, trading_session_id → trading_sessions) were
    # already created inline in PR 2's CREATE TABLE trades. Do NOT drop them here.
    # Creating the referenced tables activates the existing FKs automatically.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_strategy_setups_setup_id', table_name='strategy_setups')
    op.drop_table('strategy_setups')
    op.drop_index('ix_risk_profiles_strategy_id', table_name='risk_profiles')
    op.drop_table('risk_profiles')
    op.drop_table('strategies')
    op.drop_table('setups')
    # ### end Alembic commands ###
